# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python script tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Test Programming Fundamentals Python Part 1 - ex1
      run: |
        cd programming_fundamentals/python_part_1
        pip install -r requirements.txt
        VALUE=$(echo $((1 + RANDOM % 10)))
        python example1.py $VALUE
    - name: Test Programming Fundamentals Python Part 1 - ex2
      run: |
        cd programming_fundamentals/python_part_1
        pip install -r requirements.txt
        echo "Anne Marie Janeene Anastasia Eileen" > names.txt
        cat names.txt | while read -r line; do echo "$line" | grep -oP '(\S+)' | shuf -n $((RANDOM%2+1)) | paste -s -d' '; done < file.txt
        cat file.txt
        python example2.py Anne
    - name: Test Programming Fundamentals Python Part 1 - ex3
      run: |
        cd programming_fundamentals/python_part_1
        pip install -r requirements.txt
        python example3.py
